"""add cascade deletes

Revision ID: 8bb3d1091273
Revises: c3231a5641c7
Create Date: 2026-10-05 19:12:15.368172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb3d1091273'
down_revision: Union[str, Sequence[str], None] = 'c3231a5641c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_product_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_product_id_fkey'), 'review', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
